version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env # Çevresel değişkenler .env dosyasından okunacak
    environment:
      NODE_ENV: production # Çevre ortamı 'production' olarak ayarlanıyor
    restart: unless-stopped
